### ISSUE TITLE
Divide by norm_clip in eta calculation

### ISSUE THREAD

**Issue by brandonedmunds2** [facebookresearch/bounding_data_reconstruction#3]
Hello,
In train_classifier.py, line 144, `etas_batch = fil_accountant(rng, opt_state, batch) / cfg.sigma / cfg.norm_clip`, there is a division by `cfg.norm_clip`. I think this is unintentional since I do not think it is in the paper, also the rest of the code supports `cfg.norm_clip=0`. I think this would have a large impact on the results.
Thank you for your help

**Comment by cg563** [comment]
I think having this division by `cfg.norm_clip` is correct because the Gaussian noise added has scale `cfg.norm_clip * cfg.sigma` (see https://github.com/facebookresearch/bounding_data_reconstruction/blob/main/trainer.py#L81). There is actually a typo in Eq. 1 in the paper because it's missing the C factor: Eq. 16 in https://arxiv.org/pdf/2102.11673.pdf applies when the Gaussian noise added has variance `sigma^2`, not `C^2 * sigma^2`.

**Comment by brandonedmunds2** [comment]
I see, my mistake. Thank you for your time

**Comment by cg563** [comment]
Thanks for finding this typo! I will update the arXiv version of the paper shortly.
